"""
事件定义库——所有事件常量的唯一来源。

四大类别：DAILY_EVENTS（日常）、ENVIRONMENT_EVENTS（环境）、CRITICAL_EVENTS（关键）、
SCHEDULE_EVENTS（日程骨架）。摇篮和世界层共用同一份定义。

[INPUT]: events.Event 数据类
[OUTPUT]: DAILY_EVENTS, ENVIRONMENT_EVENTS, CRITICAL_EVENTS, SCHEDULE_EVENTS, ALL_EVENTS, get_event
[POS]: 事件定义层，被 events/__init__.py route_events/roll_emergent_event 和 cradle/events.py roll_events 消费
[PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
"""

from __future__ import annotations

from events import Event


# ============================================================
# 日常事件 — 规则引擎处理，无需 LLM
# ============================================================

DAILY_EVENTS = [
    Event(
        name="feeding_difficulty",
        category="daily",
        display_name="Feeding Difficulty",
        description="Baby has trouble feeding, needs position adjustment or soothing.",
        sensory_channels=["touch", "smell"],
        intensity=0.3,
        requires_parent=False,
        phase_range=(0, 3),
    ),
    Event(
        name="sleep_disruption",
        category="daily",
        display_name="Sleep Disruption",
        description="Baby wakes up during sleep, cannot self-soothe.",
        sensory_channels=["touch"],
        intensity=0.2,
        requires_parent=False,
        phase_range=(0, 7),
    ),
    Event(
        name="body_discomfort",
        category="daily",
        display_name="Body Discomfort",
        description="General discomfort (gas, wet diaper, etc.), handled by nanny.",
        sensory_channels=["touch"],
        intensity=0.2,
        requires_parent=False,
        phase_range=(0, 5),
    ),
    Event(
        name="routine_sound",
        category="daily",
        display_name="Routine Sound",
        description="Everyday household sounds (faucet, doorbell, phone, TV).",
        sensory_channels=["hearing"],
        intensity=0.15,
        requires_parent=False,
        phase_range=(0, 5),
    ),
    Event(
        name="gentle_touch",
        category="daily",
        display_name="Gentle Touch",
        description="Nanny or family member gently stroking, hugging.",
        sensory_channels=["touch"],
        intensity=0.1,
        requires_parent=False,
        phase_range=(0, 4),
    ),
    Event(
        name="toy_interaction",
        category="daily",
        display_name="Toy Interaction",
        description="Interacting with hanging toys or rattles.",
        sensory_channels=["vision", "touch", "hearing"],
        intensity=0.2,
        requires_parent=False,
        phase_range=(1, 6),
    ),
    Event(
        name="outdoor_walk",
        category="daily",
        display_name="Outdoor Walk",
        description="Taken outside, feeling wind, sunlight, new sounds.",
        sensory_channels=["touch", "vision", "hearing", "smell"],
        intensity=0.3,
        requires_parent=False,
        phase_range=(1, 11),
    ),
    # ---- 增强：喂养/睡眠/体格/游戏 ----
    Event(
        name="teething_discomfort",
        category="daily",
        display_name="Teething Discomfort",
        description="Gums swollen and painful, drooling increases, biting everything.",
        sensory_channels=["touch"],
        intensity=0.3,
        requires_parent=False,
        phase_range=(3, 7),
    ),
    Event(
        name="picky_eating",
        category="daily",
        display_name="Picky Eating",
        description="Refuses certain foods, pushes plate away, only wants familiar tastes.",
        sensory_channels=["smell", "touch"],
        intensity=0.2,
        requires_parent=False,
        phase_range=(7, 9),
    ),
    Event(
        name="common_cold",
        category="daily",
        display_name="Common Cold",
        description="Runny nose, mild cough, slightly fussy but still alert.",
        sensory_channels=["touch"],
        intensity=0.25,
        requires_parent=False,
        phase_range=(0, 11),
    ),
    Event(
        name="sleep_regression",
        category="daily",
        display_name="Sleep Regression",
        description="After weeks of sleeping through, suddenly waking multiple times.",
        sensory_channels=["touch"],
        intensity=0.3,
        requires_parent=False,
        phase_range=(2, 7),
    ),
    Event(
        name="play_session",
        category="daily",
        display_name="Play Session",
        description="Engaging with age-appropriate toys and activities.",
        sensory_channels=["vision", "touch", "hearing"],
        intensity=0.2,
        requires_parent=False,
        phase_range=(1, 11),
    ),
    Event(
        name="growth_spurt",
        category="daily",
        display_name="Growth Spurt",
        description="Increased appetite, slight fussiness, measurable growth.",
        sensory_channels=["touch"],
        intensity=0.15,
        requires_parent=False,
        phase_range=(0, 11),
    ),
]

# ============================================================
# 环境事件 — 需要 LLM 处理宝宝反应
# ============================================================

ENVIRONMENT_EVENTS = [
    Event(
        name="thunderstorm",
        category="environment",
        display_name="Thunderstorm",
        description="Sudden thunder and lightning. Windows rattle, ozone smell in the air.",
        sensory_channels=["hearing", "vision"],
        intensity=0.8,
        requires_parent=False,
        phase_range=(0, 7),
        weight=0.3,
        requires_tags=["rainy_climate"],
    ),
    Event(
        name="hearing_music",
        category="environment",
        display_name="Hearing Music",
        description="Music fills the room — melody, rhythm, harmony wash over the senses.",
        sensory_channels=["hearing"],
        intensity=0.5,
        requires_parent=False,
        phase_range=(0, 3),
        weight=0.6,
        requires_tags=["musical_home"],
    ),
    Event(
        name="sunbeam_on_floor",
        category="environment",
        display_name="Sunbeam on Floor",
        description="A beam of sunlight through the window, dust dancing in the light.",
        sensory_channels=["vision"],
        intensity=0.3,
        requires_parent=False,
        phase_range=(1, 5),
        weight=0.6,
        requires_tags=["sunny_climate"],
    ),
    Event(
        name="pet_encounter",
        category="environment",
        display_name="Pet Encounter",
        description="The family cat or dog approaches the baby. Animal smell, fur, sounds.",
        sensory_channels=["vision", "touch", "smell", "hearing"],
        intensity=0.6,
        requires_parent=False,
        phase_range=(1, 6),
        weight=0.4,
        requires_tags=["has_pet"],
    ),
    Event(
        name="mirror_discovery",
        category="environment",
        display_name="Mirror Discovery",
        description="Baby sees themselves in a mirror. Who is that moving figure?",
        sensory_channels=["vision"],
        intensity=0.5,
        requires_parent=False,
        phase_range=(2, 6),
        weight=0.5,
    ),
    Event(
        name="water_play",
        category="environment",
        display_name="Water Play",
        description="During bath or water play — splashing, temperature, flow.",
        sensory_channels=["touch", "vision", "hearing"],
        intensity=0.4,
        requires_parent=False,
        phase_range=(2, 7),
        weight=0.5,
    ),
    Event(
        name="new_food_taste",
        category="environment",
        display_name="New Food",
        description="Encounter with a new food. Unfamiliar taste, texture, temperature.",
        sensory_channels=["smell", "touch"],
        intensity=0.5,
        requires_parent=False,
        phase_range=(3, 6),
        weight=0.6,
    ),
    Event(
        name="cooking_smell",
        category="environment",
        display_name="Cooking Smell",
        description="Rich aroma drifts in from the kitchen — garlic, soup, or baking bread.",
        sensory_channels=["smell"],
        intensity=0.3,
        requires_parent=False,
        phase_range=(0, 5),
        weight=0.6,
    ),
    Event(
        name="being_held_new_person",
        category="environment",
        display_name="New Arms",
        description="A new person picks the baby up. Different hold, different warmth, different heartbeat rhythm.",
        sensory_channels=["touch", "smell", "hearing"],
        intensity=0.5,
        requires_parent=False,
        phase_range=(0, 3),
        weight=0.6,
        requires_tags=["bustling_home"],
    ),
    Event(
        name="light_change",
        category="environment",
        display_name="Light Change",
        description="Room light shifts — curtains drawn, lamp switched, or sunset glow creeping across the ceiling.",
        sensory_channels=["vision"],
        intensity=0.2,
        requires_parent=False,
        phase_range=(0, 2),
        weight=0.7,
    ),
    Event(
        name="rain_sound",
        category="environment",
        display_name="Rain Sound",
        description="Steady patter of rain against the window. A rhythmic, enveloping white noise.",
        sensory_channels=["hearing"],
        intensity=0.3,
        requires_parent=False,
        phase_range=(0, 5),
        weight=0.5,
        requires_tags=["rainy_climate"],
    ),
    Event(
        name="skin_to_skin",
        category="environment",
        display_name="Skin Contact",
        description="Bare chest against bare chest. Direct warmth, parent's heartbeat, steady breathing.",
        sensory_channels=["touch", "hearing", "smell"],
        intensity=0.4,
        requires_parent=False,
        phase_range=(0, 2),
        weight=0.7,
    ),
    Event(
        name="fan_breeze",
        category="environment",
        display_name="Breeze",
        description="A gentle breeze from a fan or open window brushes across the skin.",
        sensory_channels=["touch"],
        intensity=0.2,
        requires_parent=False,
        phase_range=(0, 3),
        weight=0.5,
    ),
    Event(
        name="fabric_texture",
        category="environment",
        display_name="New Texture",
        description="A different blanket or clothing — rough wool, cool silk, fluffy towel against the skin.",
        sensory_channels=["touch"],
        intensity=0.3,
        requires_parent=False,
        phase_range=(0, 3),
        weight=0.5,
    ),
    Event(
        name="bird_song",
        category="environment",
        display_name="Bird Song",
        description="Clear bird calls from outside the window. High-pitched, unpredictable, alive.",
        sensory_channels=["hearing"],
        intensity=0.25,
        requires_parent=False,
        phase_range=(0, 5),
        weight=0.5,
        excludes_tags=["urban_apartment"],
    ),
    Event(
        name="warm_bath_sensation",
        category="environment",
        display_name="Warm Water",
        description="Warm water envelops the body for the first few times. Weightlessness, warmth, new world.",
        sensory_channels=["touch", "proprioception"],
        intensity=0.4,
        requires_parent=False,
        phase_range=(0, 2),
        weight=0.5,
    ),
    Event(
        name="hiccups",
        category="environment",
        display_name="Hiccups",
        description="Rhythmic, involuntary spasms. The body doing something the mind cannot control.",
        sensory_channels=["proprioception"],
        intensity=0.2,
        requires_parent=False,
        phase_range=(0, 2),
        weight=0.6,
    ),
    Event(
        name="door_slam",
        category="environment",
        display_name="Door Slam",
        description="A sudden bang as a door slams shut. Sharp, brief, startling.",
        sensory_channels=["hearing"],
        intensity=0.6,
        requires_parent=False,
        phase_range=(0, 5),
        weight=0.3,
        requires_tags=["bustling_home"],
    ),
    Event(
        name="loud_argument",
        category="environment",
        display_name="Loud Argument",
        description="Nearby people arguing loudly. Sharp sounds, emotional tension.",
        sensory_channels=["hearing"],
        intensity=0.7,
        requires_parent=False,
        phase_range=(0, 11),
        weight=0.2,
        requires_tags=["bustling_home"],
    ),
    Event(
        name="stranger_visit",
        category="environment",
        display_name="Stranger Visit",
        description="An unfamiliar person appears — strange voice and smell.",
        sensory_channels=["vision", "hearing", "smell"],
        intensity=0.5,
        requires_parent=False,
        phase_range=(2, 8),
        weight=0.5,
    ),
    Event(
        name="other_baby_cry",
        category="environment",
        display_name="Other Baby Crying",
        description="Another baby's cry reaches them. A fellow creature's distress signal.",
        sensory_channels=["hearing"],
        intensity=0.5,
        requires_parent=False,
        phase_range=(0, 5),
        weight=0.3,
        requires_tags=["has_siblings"],
    ),
    Event(
        name="darkness",
        category="environment",
        display_name="Darkness",
        description="Room goes dark suddenly, or waking in complete darkness for the first time.",
        sensory_channels=["vision"],
        intensity=0.6,
        requires_parent=False,
        phase_range=(1, 7),
        weight=0.4,
    ),
    Event(
        name="falling_object",
        category="environment",
        display_name="Falling Object",
        description="An object falls from a table, making a crash. First experience of cause and effect.",
        sensory_channels=["hearing", "vision"],
        intensity=0.4,
        requires_parent=False,
        phase_range=(2, 5),
        weight=0.4,
    ),
    Event(
        name="peer_encounter",
        category="environment",
        display_name="Peer Encounter",
        description="Another child of similar age appears. First sight of 'someone like me'.",
        sensory_channels=["vision", "hearing"],
        intensity=0.5,
        requires_parent=False,
        phase_range=(5, 11),
        weight=0.5,
    ),
    Event(
        name="drawing_discovery",
        category="environment",
        display_name="Drawing Discovery",
        description="Hand grabs a crayon or brush, leaves marks on paper. They can change the world.",
        sensory_channels=["vision", "touch"],
        intensity=0.5,
        requires_parent=False,
        phase_range=(5, 9),
        weight=0.5,
    ),
    Event(
        name="story_heard",
        category="environment",
        display_name="Story Heard",
        description="Someone is telling a story — with characters, plot, and conflict.",
        sensory_channels=["hearing"],
        intensity=0.4,
        requires_parent=False,
        phase_range=(6, 11),
        weight=0.6,
    ),
    # ---- 增强：情绪/想象力/共情 ----
    Event(
        name="tantrum_trigger",
        category="environment",
        display_name="Tantrum Trigger",
        description="Something small sets off a disproportionate emotional explosion.",
        sensory_channels=["hearing", "touch"],
        intensity=0.7,
        requires_parent=False,
        phase_range=(6, 9),
        weight=0.5,
    ),
    Event(
        name="imaginary_friend_appears",
        category="environment",
        display_name="Imaginary Friend",
        description="The child begins talking to someone invisible, with a name and personality.",
        sensory_channels=["hearing", "vision"],
        intensity=0.3,
        requires_parent=False,
        phase_range=(8, 11),
        weight=0.4,
    ),
    Event(
        name="first_drawing",
        category="environment",
        display_name="First Drawing",
        description="Crayon meets paper. Something intentional appears for the first time.",
        sensory_channels=["vision", "touch"],
        intensity=0.4,
        requires_parent=False,
        phase_range=(5, 9),
        weight=0.5,
    ),
    Event(
        name="empathy_moment",
        category="environment",
        display_name="Empathy Moment",
        description="Another child is crying. How does this child respond?",
        sensory_channels=["hearing", "vision"],
        intensity=0.4,
        requires_parent=False,
        phase_range=(5, 11),
        weight=0.4,
    ),

    # ---- 照护模式驱动 ----
    Event(
        name="nanny_lullaby",
        category="environment",
        display_name="Nanny Lullaby",
        description="The nanny hums a folk lullaby from her hometown. A melody the parents never sing.",
        sensory_channels=["hearing"],
        intensity=0.3,
        requires_parent=False,
        phase_range=(0, 3),
        weight=0.6,
        requires_tags=["nanny_care"],
    ),
    Event(
        name="nanny_handover",
        category="environment",
        display_name="Nanny Handover",
        description="The nanny hands the baby to the parent. Different smell, different hold, a small jolt of change.",
        sensory_channels=["touch", "smell"],
        intensity=0.4,
        requires_parent=False,
        phase_range=(0, 3),
        weight=0.5,
        requires_tags=["nanny_care"],
    ),
    Event(
        name="grandparent_story",
        category="environment",
        display_name="Grandparent Story",
        description="A grandparent's slow, weathered voice telling old tales. Unhurried words, warm lap.",
        sensory_channels=["hearing", "touch"],
        intensity=0.3,
        requires_parent=False,
        phase_range=(0, 7),
        weight=0.6,
        requires_tags=["grandparent_care"],
    ),
    Event(
        name="grandparent_spoiling",
        category="environment",
        display_name="Grandparent Spoiling",
        description="A grandparent sneaks extra treats or breaks a small rule. Conspiratorial warmth.",
        sensory_channels=["touch", "smell"],
        intensity=0.3,
        requires_parent=False,
        phase_range=(3, 9),
        weight=0.5,
        requires_tags=["grandparent_care"],
    ),

    # ---- 经济条件驱动 ----
    Event(
        name="new_toy_arrival",
        category="environment",
        display_name="New Toy",
        description="A new toy appears — bright colors, unfamiliar shape, rich texture.",
        sensory_channels=["vision", "touch"],
        intensity=0.4,
        requires_parent=False,
        phase_range=(1, 7),
        weight=0.5,
        requires_tags=["wealthy_family"],
    ),
    Event(
        name="household_noise",
        category="environment",
        display_name="Household Machine",
        description="A washing machine, vacuum, or blender roars to life. Mechanical rumble fills the space.",
        sensory_channels=["hearing"],
        intensity=0.4,
        requires_parent=False,
        phase_range=(0, 4),
        weight=0.5,
        requires_tags=["modest_family"],
    ),
    Event(
        name="shared_space",
        category="environment",
        display_name="Shared Space",
        description="The baby's sleeping area is in the living room. Voices, TV, footsteps — never truly silent.",
        sensory_channels=["hearing", "vision"],
        intensity=0.3,
        requires_parent=False,
        phase_range=(0, 5),
        weight=0.5,
        requires_tags=["modest_family"],
    ),
    Event(
        name="garden_discovery",
        category="environment",
        display_name="Garden Discovery",
        description="Grass underfoot, leaves overhead, insects buzzing. A living world of textures and smells.",
        sensory_channels=["touch", "vision", "smell"],
        intensity=0.4,
        requires_parent=False,
        phase_range=(2, 7),
        weight=0.5,
        requires_tags=["suburban_house"],
    ),

    # ---- 文化氛围驱动 ----
    Event(
        name="reading_aloud",
        category="environment",
        display_name="Reading Aloud",
        description="A calm voice reads from a book. Words flow in cadence, pages turn with a soft rustle.",
        sensory_channels=["hearing"],
        intensity=0.3,
        requires_parent=False,
        phase_range=(0, 5),
        weight=0.6,
        requires_tags=["bookish_home"],
    ),
    Event(
        name="second_language",
        category="environment",
        display_name="Second Language",
        description="Someone speaks in a different language. Strange rhythm, unfamiliar phonemes, new music.",
        sensory_channels=["hearing"],
        intensity=0.4,
        requires_parent=False,
        phase_range=(0, 7),
        weight=0.6,
        requires_tags=["bilingual_home"],
    ),
    Event(
        name="prayer_chant",
        category="environment",
        display_name="Prayer Chant",
        description="Low, rhythmic chanting or prayer fills the room. Solemn tones, incense, candlelight.",
        sensory_channels=["hearing", "smell"],
        intensity=0.3,
        requires_parent=False,
        phase_range=(0, 7),
        weight=0.5,
        requires_tags=["religious_home"],
    ),
    Event(
        name="sibling_play",
        category="environment",
        display_name="Sibling Play",
        description="An older sibling makes funny faces, shakes a rattle, or pokes gently. Clumsy but earnest.",
        sensory_channels=["vision", "touch", "hearing"],
        intensity=0.4,
        requires_parent=False,
        phase_range=(0, 5),
        weight=0.6,
        requires_tags=["has_siblings"],
    ),
    Event(
        name="sibling_conflict",
        category="environment",
        display_name="Sibling Conflict",
        description="The sibling snatches a toy or yells nearby. A burst of unexpected aggression.",
        sensory_channels=["hearing", "vision"],
        intensity=0.6,
        requires_parent=False,
        phase_range=(2, 9),
        weight=0.4,
        requires_tags=["has_siblings"],
    ),

    # ---- 乡村特有 ----
    Event(
        name="animal_sounds",
        category="environment",
        display_name="Farm Sounds",
        description="Roosters crow, dogs bark in the distance, insects hum. The soundscape of open land.",
        sensory_channels=["hearing"],
        intensity=0.3,
        requires_parent=False,
        phase_range=(0, 5),
        weight=0.6,
        requires_tags=["rural_home"],
    ),
    Event(
        name="earth_smell",
        category="environment",
        display_name="Earth Smell",
        description="The scent of damp earth, cut grass, or wood smoke drifts in through open windows.",
        sensory_channels=["smell"],
        intensity=0.25,
        requires_parent=False,
        phase_range=(0, 5),
        weight=0.5,
        requires_tags=["rural_home"],
    ),

    # ---- 城市特有 ----
    Event(
        name="traffic_noise",
        category="environment",
        display_name="Traffic Noise",
        description="Horns honking, engines rumbling, sirens wailing somewhere below the window.",
        sensory_channels=["hearing"],
        intensity=0.5,
        requires_parent=False,
        phase_range=(0, 5),
        weight=0.4,
        requires_tags=["urban_apartment"],
    ),
    Event(
        name="elevator_ride",
        category="environment",
        display_name="Elevator Ride",
        description="The floor shifts, stomach drops slightly. Enclosed space, mechanical hum, strangers' perfume.",
        sensory_channels=["proprioception", "smell"],
        intensity=0.4,
        requires_parent=False,
        phase_range=(0, 5),
        weight=0.4,
        requires_tags=["urban_apartment"],
    ),
]

# ============================================================
# 关键事件 — 暂停等待父母介入
# ============================================================

CRITICAL_EVENTS = [
    Event(
        name="high_fever",
        category="critical",
        display_name="High Fever",
        description="The baby's temperature has spiked. Face flushed, spirit listless.",
        sensory_channels=["touch"],
        intensity=0.9,
        requires_parent=True,
        phase_range=(0, 7),
        weight=0.15,
        parent_choices=[
            {"action": "comfort", "display": "Hold and comfort gently", "effect": "Enhanced sense of safety"},
            {"action": "medical", "display": "Seek medical help immediately", "effect": "Learns that asking for help works"},
            {"action": "observe", "display": "Observe and wait", "effect": "Self-recovery awareness"},
        ],
    ),
    Event(
        name="prolonged_crying",
        category="critical",
        display_name="Prolonged Crying",
        description="The baby has been crying for over an hour. The nanny cannot soothe them.",
        sensory_channels=["hearing", "touch"],
        intensity=0.8,
        requires_parent=True,
        phase_range=(0, 4),
        weight=0.2,
        parent_choices=[
            {"action": "hold_and_rock", "display": "Hold and rock gently", "effect": "'Being responded to' → secure attachment foundation"},
            {"action": "let_cry", "display": "Let them cry it out", "effect": "Self-soothing ability / or feeling ignored"},
            {"action": "sing", "display": "Sing a lullaby", "effect": "Sound becomes a source of comfort"},
        ],
    ),
    Event(
        name="first_fall",
        category="critical",
        display_name="First Fall",
        description="The baby fell while trying to crawl or stand. Startled but not seriously hurt.",
        sensory_channels=["touch", "proprioception"],
        intensity=0.6,
        requires_parent=True,
        phase_range=(3, 5),
        weight=0.5,
        parent_choices=[
            {"action": "rush_over", "display": "Rush over and pick up", "effect": "'Falling = danger' memory reinforced"},
            {"action": "encourage", "display": "Encourage them to get up", "effect": "'I can recover' → resilience"},
            {"action": "calm_check", "display": "Calmly check for injuries", "effect": "'Falling isn't scary' → safe exploration"},
        ],
    ),
    Event(
        name="first_word_moment",
        category="critical",
        display_name="First Word",
        description="The baby uttered their first meaningful word — perhaps 'mama', 'dada', or a familiar object.",
        sensory_channels=["hearing"],
        intensity=0.7,
        requires_parent=True,
        phase_range=(5, 6),
        weight=0.9,
        parent_choices=[
            {"action": "celebrate", "display": "Celebrate and repeat the word", "effect": "Language = gets attention and response"},
            {"action": "teach_more", "display": "Teach more words", "effect": "Accelerates language development"},
            {"action": "gentle_smile", "display": "Smile and respond gently", "effect": "Language = natural communication"},
        ],
    ),
    Event(
        name="nightmare",
        category="critical",
        display_name="Nightmare",
        description="The baby woke screaming in the night. Clearly terrified, hard to soothe.",
        sensory_channels=["hearing", "touch"],
        intensity=0.8,
        requires_parent=True,
        phase_range=(3, 8),
        weight=0.25,
        parent_choices=[
            {"action": "hold_tight", "display": "Hold tight and reassure safety", "effect": "'Someone is there when scared' → secure base"},
            {"action": "light_on", "display": "Turn on the light", "effect": "'Seeing = safe' → visual dependence"},
            {"action": "stay_nearby", "display": "Stay nearby, let them calm down", "effect": "'I can recover from fear'"},
        ],
    ),
    Event(
        name="naming_ceremony",
        category="critical",
        display_name="Naming Ceremony",
        description="It's time to give this child a name.",
        sensory_channels=[],
        intensity=0.5,
        requires_parent=True,
        phase_range=(1, 6),
        weight=0.0,
        parent_choices=[
            {"action": "name", "display": "Give them a name", "effect": "Starting point of self-awareness"},
        ],
    ),
    Event(
        name="first_defiance",
        category="critical",
        display_name="First Defiance",
        description="The baby said 'no' for the first time — shaking head, pushing away, or speaking the word.",
        sensory_channels=["hearing"],
        intensity=0.6,
        requires_parent=True,
        phase_range=(6, 8),
        weight=0.7,
        parent_choices=[
            {"action": "respect", "display": "Respect their choice", "effect": "'My will matters' → autonomy"},
            {"action": "insist", "display": "Insist firmly", "effect": "'Rules override will' → compliance or rebellion"},
            {"action": "negotiate", "display": "Offer alternatives", "effect": "'After refusal, negotiation is possible' → negotiation ability"},
        ],
    ),
    Event(
        name="emotional_storm",
        category="critical",
        display_name="Emotional Storm",
        description="The baby erupted over something small — screaming, throwing things, rolling on the floor.",
        sensory_channels=["hearing", "touch"],
        intensity=0.8,
        requires_parent=True,
        phase_range=(7, 9),
        weight=0.6,
        parent_choices=[
            {"action": "validate", "display": "Kneel down: 'I know you're upset'", "effect": "Emotion acknowledged → emotional regulation"},
            {"action": "distract", "display": "Redirect attention", "effect": "'Avoid bad feelings' → avoidance strategy"},
            {"action": "boundary", "display": "Set calm but firm boundary", "effect": "'Emotions OK, but behavior has limits'"},
            {"action": "ignore", "display": "Wait it out in silence", "effect": "Self-regulation / or emotional suppression"},
        ],
    ),
    Event(
        name="first_lie",
        category="critical",
        display_name="First Lie",
        description="The baby told an obvious untruth to avoid punishment or get something.",
        sensory_channels=["hearing"],
        intensity=0.5,
        requires_parent=True,
        phase_range=(8, 11),
        weight=0.4,
        parent_choices=[
            {"action": "curious", "display": "Ask curiously: 'Really? What happened?'", "effect": "'Honesty can be guided, not feared'"},
            {"action": "confront", "display": "Point out the truth directly", "effect": "'Lies will be discovered' → honesty pressure"},
            {"action": "discuss_why", "display": "Discuss why they wanted to lie", "effect": "Understanding motive → moral reasoning"},
        ],
    ),
    Event(
        name="separation_test",
        category="critical",
        display_name="Separation Test",
        description="Parent needs to leave for a while. The baby faces their first prolonged absence.",
        sensory_channels=["vision", "hearing"],
        intensity=0.7,
        requires_parent=True,
        phase_range=(3, 7),
        weight=0.3,
        parent_choices=[
            {"action": "explain_return", "display": "Explain you'll return, then leave", "effect": "Predictable separation → secure attachment"},
            {"action": "sneak_away", "display": "Sneak away while distracted", "effect": "Unpredictable disappearance → anxious attachment"},
            {"action": "gradual", "display": "Start with short absences, then extend", "effect": "Gradual adaptation → separation tolerance"},
        ],
    ),
    # ---- 增强：喂养/睡眠/如厕/入园/夜惊/想象伙伴 ----
    Event(
        name="food_allergy",
        category="critical",
        display_name="Food Allergy",
        description="After trying new food, face swells, skin rashes appear.",
        sensory_channels=["touch", "smell"],
        intensity=0.8,
        requires_parent=True,
        phase_range=(3, 5),
        weight=0.15,
        parent_choices=[
            {"action": "rush_hospital", "display": "Rush to hospital", "effect": "Safety first → medical trust"},
            {"action": "observe_carefully", "display": "Observe symptoms carefully", "effect": "Calm assessment → resilience"},
            {"action": "remove_food", "display": "Remove food, apply cold compress", "effect": "Practical response → problem-solving"},
        ],
    ),
    Event(
        name="room_separation",
        category="critical",
        display_name="Room Separation",
        description="It might be time for the child to sleep in their own room.",
        sensory_channels=["vision", "hearing"],
        intensity=0.5,
        requires_parent=True,
        phase_range=(5, 7),
        weight=0.3,
        parent_choices=[
            {"action": "gradual_transition", "display": "Gradual transition over weeks", "effect": "Independence + security balance"},
            {"action": "immediate", "display": "Move to own room tonight", "effect": "Independence boost / stress risk"},
            {"action": "delay", "display": "Not ready yet, wait longer", "effect": "Continued co-sleeping security"},
        ],
    ),
    Event(
        name="toilet_training",
        category="critical",
        display_name="Toilet Training",
        description="The child shows signs of readiness. Time to start?",
        sensory_channels=["touch", "proprioception"],
        intensity=0.4,
        requires_parent=True,
        phase_range=(7, 8),
        weight=0.6,
        parent_choices=[
            {"action": "patient_encourage", "display": "Praise every attempt", "effect": "Autonomy + positive reinforcement"},
            {"action": "strict_schedule", "display": "Set strict bathroom schedule", "effect": "Discipline / pressure risk"},
            {"action": "wait_readiness", "display": "Wait for more readiness signs", "effect": "No pressure → natural timing"},
        ],
    ),
    Event(
        name="kindergarten_entry",
        category="critical",
        display_name="Kindergarten Entry",
        description="First day at kindergarten. The child faces a room full of strangers without parents.",
        sensory_channels=["vision", "hearing", "touch"],
        intensity=0.8,
        requires_parent=True,
        phase_range=(8, 8),
        weight=0.9,
        parent_choices=[
            {"action": "stay_briefly", "display": "Stay for the first hour, then leave", "effect": "Gradual separation → adapted"},
            {"action": "quick_goodbye", "display": "Quick hug and confident goodbye", "effect": "'Parent believes I can do this' → confidence"},
            {"action": "sneak_away", "display": "Slip away while distracted", "effect": "Unpredictable abandonment → anxiety"},
        ],
    ),
    Event(
        name="night_terror",
        category="critical",
        display_name="Night Terror",
        description="Child sits up screaming, eyes open but unseeing. Cannot be woken.",
        sensory_channels=["hearing", "touch"],
        intensity=0.7,
        requires_parent=True,
        phase_range=(8, 10),
        weight=0.2,
        parent_choices=[
            {"action": "stay_safe", "display": "Stay nearby, keep them safe", "effect": "Safety without interference → passes naturally"},
            {"action": "try_wake", "display": "Try to wake them up", "effect": "Prolonged confusion / disorientation"},
            {"action": "hold_gently", "display": "Hold gently until it passes", "effect": "Physical safety anchor"},
        ],
    ),
    Event(
        name="imaginary_friend_discovery",
        category="critical",
        display_name="Imaginary Friend Discovery",
        description="You realize your child has been having conversations with an invisible friend.",
        sensory_channels=["hearing"],
        intensity=0.3,
        requires_parent=True,
        phase_range=(8, 11),
        weight=0.35,
        parent_choices=[
            {"action": "curious", "display": "Ask about the friend with interest", "effect": "Imagination validated → creativity"},
            {"action": "worried", "display": "Express concern, discourage it", "effect": "Shame / hidden inner world"},
            {"action": "play_along", "display": "Set a place at the table for them", "effect": "Full acceptance → trust + creativity"},
        ],
    ),
]

# ============================================================
# 日程骨架事件 — 构成每日时间表的基本结构
# ============================================================

SCHEDULE_EVENTS = [
    Event(name="wake_up", category="schedule", display_name="Wake Up",
          description="Baby wakes up.", sensory_channels=["hearing", "vision"],
          intensity=0.1, requires_parent=False, phase_range=(0, 11),
          hour_range=(5, 8), duration_hours=0.5, generates_next="breakfast"),
    Event(name="breakfast", category="schedule", display_name="Breakfast",
          description="Morning meal.", sensory_channels=["taste", "touch"],
          intensity=0.1, requires_parent=False, phase_range=(0, 11),
          hour_range=(6, 9), duration_hours=0.5),
    Event(name="feeding", category="schedule", display_name="Feeding",
          description="Feeding time.", sensory_channels=["taste", "touch", "smell"],
          intensity=0.2, requires_parent=False, phase_range=(0, 3),
          hour_range=(0, 24), duration_hours=0.5),
    Event(name="nap", category="schedule", display_name="Nap",
          description="Nap time.", sensory_channels=["touch"],
          intensity=0.1, requires_parent=False, phase_range=(0, 5),
          hour_range=(9, 15), duration_hours=1.5),
    Event(name="lunch", category="schedule", display_name="Lunch",
          description="Midday meal.", sensory_channels=["taste", "touch"],
          intensity=0.1, requires_parent=False, phase_range=(0, 11),
          hour_range=(11, 13), duration_hours=0.5),
    Event(name="dinner", category="schedule", display_name="Dinner",
          description="Evening meal.", sensory_channels=["taste", "touch"],
          intensity=0.1, requires_parent=False, phase_range=(0, 11),
          hour_range=(17, 19), duration_hours=0.5),
    Event(name="bath", category="schedule", display_name="Bath",
          description="Bath time.", sensory_channels=["touch", "proprioception"],
          intensity=0.2, requires_parent=False, phase_range=(0, 4),
          hour_range=(18, 20), duration_hours=0.5),
    Event(name="sleep", category="schedule", display_name="Sleep",
          description="Bedtime.", sensory_channels=["touch"],
          intensity=0.1, requires_parent=False, phase_range=(0, 11),
          hour_range=(19, 22), duration_hours=10.0),
    Event(name="morning_play", category="schedule", display_name="Morning Play",
          description="Free play in the morning.", sensory_channels=["vision", "touch"],
          intensity=0.2, requires_parent=False, phase_range=(2, 11),
          hour_range=(8, 12), duration_hours=2.0,
          excludes_tags=["enrolled_school"]),
    Event(name="afternoon_activity", category="schedule", display_name="Afternoon Activity",
          description="Afternoon activities at home.", sensory_channels=["vision", "touch"],
          intensity=0.2, requires_parent=False, phase_range=(2, 11),
          hour_range=(14, 17), duration_hours=2.0,
          excludes_tags=["enrolled_school"]),
    Event(name="family_time", category="schedule", display_name="Family Time",
          description="Evening family interaction.", sensory_channels=["hearing", "vision", "touch"],
          intensity=0.2, requires_parent=False, phase_range=(0, 11),
          hour_range=(18, 21), duration_hours=1.0),
    Event(name="school_morning", category="schedule", display_name="School Morning",
          description="Morning classes.", sensory_channels=["hearing", "vision"],
          intensity=0.3, requires_parent=False, phase_range=(9, 11),
          hour_range=(8, 12), duration_hours=3.5,
          requires_tags=["enrolled_school"]),
    Event(name="school_afternoon", category="schedule", display_name="School Afternoon",
          description="Afternoon classes.", sensory_channels=["hearing", "vision"],
          intensity=0.3, requires_parent=False, phase_range=(9, 11),
          hour_range=(13, 16), duration_hours=2.5,
          requires_tags=["enrolled_school"]),
    Event(name="after_school", category="schedule", display_name="After School",
          description="After-school activities.", sensory_channels=["touch", "vision"],
          intensity=0.2, requires_parent=False, phase_range=(9, 11),
          hour_range=(15, 18), duration_hours=2.0,
          requires_tags=["enrolled_school"]),
    Event(name="homework", category="schedule", display_name="Homework",
          description="Evening homework.", sensory_channels=["vision"],
          intensity=0.2, requires_parent=False, phase_range=(9, 11),
          hour_range=(18, 21), duration_hours=1.0,
          requires_tags=["enrolled_school"]),
]

# ============================================================
# 汇总
# ============================================================

ALL_EVENTS = DAILY_EVENTS + ENVIRONMENT_EVENTS + CRITICAL_EVENTS + SCHEDULE_EVENTS

_EVENT_MAP = {e.name: e for e in ALL_EVENTS}


def get_event(name: str) -> Event | None:
    """按名称查找事件。"""
    return _EVENT_MAP.get(name)
